---
# Configuration tasks for MDATP

# Pre-configuration checks
- name: Check if onboarding file exists
  ansible.builtin.stat:
    path: "{{ mdatp_files.onboard_json }}"
  register: onboarding_status
  tags:
    - configuration
    - onboarding

# Onboarding package management
- name: Manage onboarding package
  block:
    - name: Download onboarding package
      ansible.builtin.get_url:
        url: "{{ mdatp_onboarding.package_url }}"
        dest: "{{ mdatp_paths.install_dir }}/WindowsDefenderATPOnboardingPackage.zip"
        mode: "0600"
        validate_certs: "{{ mdatp_onboarding.validate_cert }}"
      register: download_package
      until: download_package is success
      retries: 3
      delay: 5

    - name: Extract onboarding package
      ansible.builtin.unarchive:
        src: "{{ mdatp_paths.install_dir }}/WindowsDefenderATPOnboardingPackage.zip"
        dest: "{{ mdatp_paths.install_dir }}"
        remote_src: true
        creates: "{{ mdatp_files.onboard_json }}"
      register: extract_package
  when: 
    - mdatp_onboarding.enabled | bool
    - mdatp_onboarding.package_url | length > 0
    - not onboarding_status.stat.exists
  tags:
    - configuration
    - onboarding

# MDATP security configuration
- name: Configure MDATP security settings
  block:
    - name: Set real-time protection
      ansible.builtin.command:
        cmd: mdatp config real-time-protection --value {{ mdatp_security.real_time_protection | bool | ternary('enabled', 'disabled') }}
      register: rtp_config
      changed_when: rtp_config.rc == 0
      failed_when: rtp_config.rc != 0
      when: mdatp_security.real_time_protection is defined

    - name: Set cloud protection
      ansible.builtin.command:
        cmd: mdatp config cloud-enabled --value {{ mdatp_security.cloud_enabled | bool | ternary('enabled', 'disabled') }}
      register: cloud_config
      changed_when: cloud_config.rc == 0
      failed_when: cloud_config.rc != 0
      when: mdatp_security.cloud_enabled is defined
  when: mdatp_package.state != 'absent'
  tags:
    - configuration
    - security

# Update configuration
- name: Configure automatic updates
  block:
    - name: Set update settings
      ansible.builtin.command:
        cmd: mdatp config auto-update --value {{ mdatp_updates.automatic | bool | ternary('enabled', 'disabled') }}
      register: update_config
      changed_when: update_config.rc == 0
      failed_when: update_config.rc != 0
  when: 
    - mdatp_package.state != 'absent'
    - mdatp_updates.enabled | bool
  tags:
    - configuration
    - updates

# Proxy configuration
- name: Configure proxy settings
  block:
    - name: Set proxy configuration
      ansible.builtin.template:
        src: proxy.json.j2
        dest: "{{ mdatp_paths.config_dir }}/proxy.json"
        mode: "0644"
        owner: root
        group: root
      notify: restart mdatp
  when: 
    - mdatp_package.state != 'absent'
    - mdatp_proxy.enabled | bool
  tags:
    - configuration
    - proxy
