---
- name: Ensure MDATP directory exists
  ansible.builtin.file:
    path: "{{ mdatp_dir }}"
    state: directory
    mode: "0755"
    owner: root
    group: root

- name: Download Microsoft signing key
  ansible.builtin.get_url:
    url: "{{ microsoft_key_url }}"
    dest: "{{ item.dest }}"
    mode: "0644"
    force: true
  with_items:
    - { dest: "/etc/apt/trusted.gpg.d/microsoft.asc", when: ansible_os_family == "Debian" }
    - { dest: "/etc/pki/rpm-gpg/microsoft.asc", when: ansible_os_family == "RedHat" }
  when: "item.when"

- name: Import Microsoft key for RedHat-based systems
  ansible.builtin.rpm_key:
    key: "/etc/pki/rpm-gpg/microsoft.asc"
    state: present
  when: ansible_os_family == "RedHat"

- name: Add Microsoft repository for Ubuntu
  ansible.builtin.apt_repository:
    repo: "{{ ubuntu_repo_template }}"
    filename: microsoft-prod
    state: "{{ mdatp_repo_state }}"
    update_cache: true
  when: ansible_distribution == "Ubuntu"

- name: Add Microsoft repository for Debian
  ansible.builtin.apt_repository:
    repo: "{{ debian_repo_template }}"
    filename: microsoft-prod
    state: "{{ mdatp_repo_state }}"
    update_cache: true
  when: ansible_distribution == "Debian"

- name: Add Microsoft repository for RedHat-based systems
  ansible.builtin.yum_repository:
    name: "{{ redhat_repo_template.name }}"
    description: "{{ redhat_repo_template.description }}"
    baseurl: "{{ redhat_repo_template.baseurl }}"
    gpgkey: "{{ redhat_repo_template.gpgkey }}"
    gpgcheck: "{{ redhat_repo_template.gpgcheck }}"
    enabled: "{{ redhat_repo_template.enabled }}"
    state: "{{ mdatp_repo_state }}"
  when: ansible_os_family == "RedHat"

- name: Install MDATP package
  ansible.builtin.package:
    name: "{{ mdatp_package_name }}"
    state: "{{ mdatp_package_state }}"
    update_cache: "{{ ansible_os_family == 'Debian' }}"
