---
# Pre-installation tasks
- name: Create MDATP install directory
  ansible.builtin.file:
    path: "{{ mdatp_paths.install_dir }}"
    state: directory
    mode: "0755"
    owner: root
    group: root
  tags: 
    - install
    - directories

- name: Create Debian specific directories
  ansible.builtin.file:
    path: "/etc/apt/trusted.gpg.d"
    state: directory
    mode: "0755"
    owner: root
    group: root
  when: ansible_os_family == "Debian"
  tags: 
    - install
    - directories

- name: Create RedHat specific directories
  ansible.builtin.file:
    path: "/etc/pki/rpm-gpg"
    state: directory
    mode: "0755"
    owner: root
    group: root
  when: ansible_os_family == "RedHat"
  tags: 
    - install
    - directories

- name: Download Microsoft signing key for Debian
  ansible.builtin.get_url:
    url: "{{ mdatp_repository.key_url }}"
    dest: "/etc/apt/trusted.gpg.d/microsoft.asc"
    mode: "0644"
    force: true
  when: ansible_os_family == "Debian"
  register: key_download_debian
  until: key_download_debian is success
  retries: 3
  delay: 5
  tags:
    - install
    - repository

- name: Download Microsoft signing key for RedHat
  ansible.builtin.get_url:
    url: "{{ mdatp_repository.key_url }}"
    dest: "/etc/pki/rpm-gpg/microsoft.asc"
    mode: "0644"
    force: true
  when: ansible_os_family == "RedHat"
  register: key_download_redhat
  until: key_download_redhat is success
  retries: 3
  delay: 5
  tags:
    - install
    - repository

# Repository setup for different distributions
- name: Set up repository for Debian-based systems
  block:
    - name: Add Microsoft repository for Ubuntu
      ansible.builtin.apt_repository:
        repo: "{{ debian_family.repository.ubuntu.template }}"
        filename: microsoft-prod
        state: "{{ mdatp_repository.state }}"
        update_cache: true
      register: repo_add
      until: repo_add is success
      retries: 3
      delay: 5
      when: ansible_distribution == "Ubuntu"
    
    - name: Add Microsoft repository for Debian
      ansible.builtin.apt_repository:
        repo: "{{ debian_family.repository.debian.template }}"
        filename: microsoft-prod
        state: "{{ mdatp_repository.state }}"
        update_cache: true
      register: repo_add
      until: repo_add is success
      retries: 3
      delay: 5
      when: ansible_distribution == "Debian"
  when: ansible_os_family == "Debian"
  tags:
    - install
    - repository

- name: Set up repository for RedHat-based systems
  block:
    - name: Import Microsoft key for RedHat-based systems
      ansible.builtin.rpm_key:
        key: "/etc/pki/rpm-gpg/microsoft.asc"
        state: present
      register: key_import
      until: key_import is success
      retries: 3
      delay: 5

    - name: Add Microsoft repository for RedHat-based systems
      ansible.builtin.yum_repository:
        name: "{{ redhat_family.repository.template.name }}"
        description: "Microsoft Defender for Endpoint"
        baseurl: "https://packages.microsoft.com/rhel/{{ ansible_distribution_major_version }}/prod/"
        gpgkey: "{{ mdatp_repository.key_url }}"
        gpgcheck: true
        enabled: "{{ mdatp_repository.enabled }}"
        state: "{{ mdatp_repository.state }}"
      register: repo_add
      until: repo_add is success
      retries: 3
      delay: 5
  when: ansible_os_family == "RedHat"
  tags:
    - install
    - repository

# Package installation
- name: Install MDATP package
  ansible.builtin.package:
    name: mdatp
    state: "{{ mdatp_package.state | default('present') }}"
    update_cache: "{{ ansible_os_family == 'Debian' }}"
  register: package_install
  until: package_install is success
  retries: 3
  delay: 5
  notify: restart mdatp
  tags:
    - install
    - package

# Post-installation configuration
- name: Configure MDATP service
  ansible.builtin.service:
    name: mdatp
    enabled: true
    state: started
  when: mdatp_package.state != 'absent'
  tags:
    - install
    - service
